### ISSUE TITLE
tensorflowのモデルを追加した際のエラー

### ISSUE THREAD

**Issue by monarsan** [sort-font/webpage#40]
## 概要
tensorflowのモデルを読み込む際に、エラーが起きる。
 [colab](https://colab.research.google.com/drive/1jswIIPN2PIZAzk0eTqZW3k9SGVZi1bHX?hl=ja#scrollTo=TedApUOOSqcH)では正常に動いたため、どこを直せば良いのかわからない。

下記のbranchでエラーが確認できると思うので、チェックして欲しい。
https://github.com/sort-font/webpage/tree/error

## エラーメッセージ

```
❯ make run
python3 server.py
2021-08-31 17:09:26.711156: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "server.py", line 12, in <module>
    import model
  File "/Users/yokoyamaakiradai/project/flask/webpage/model.py", line 25, in <module>
    model_google = models.load_model('model/google_net')
  File "/Users/yokoyamaakiradai/project/flask/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 206, in load_model
    return saved_model_load.load(filepath, compile, options)
  File "/Users/yokoyamaakiradai/project/flask/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 155, in load
    keras_loader.finalize_objects()
  File "/Users/yokoyamaakiradai/project/flask/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 626, in finalize_objects
    self._reconstruct_all_models()
  File "/Users/yokoyamaakiradai/project/flask/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 645, in _reconstruct_all_models
    self._reconstruct_model(model_id, model, layers)
  File "/Users/yokoyamaakiradai/project/flask/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/load.py", line 661, in _reconstruct_model
    config = json_utils.decode(
  File "/Users/yokoyamaakiradai/project/flask/lib/python3.8/site-packages/tensorflow/python/keras/saving/saved_model/json_utils.py", line 62, in decode
    return json.loads(json_string, object_hook=_decode_helper)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/json/__init__.py", line 370, in loads
    return cls(**kw).decode(s)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File  #"/usr/local/Caskroom/miniconda/base/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
make: *** [run] Error 1
```

## 対処方法

- [ ] Task1

**Comment by task4233** [comment]
確認してみる

**Comment by task4233** [comment]
@monarsan 
私の環境では、指定されたブランチのコードを動かしても問題なく動いた
https://github.com/sort-font/webpage/tree/error

コミット&プッシュ忘れがないか再度確認して欲しいかも

**Comment by monarsan** [comment]
@task4233 
colabでも動いたし、taskの環境でも動いたみたいなので、俺の環境がよくなかったのかも
アンサンブルを作ったから、精度はちょっとはよくなるかも
プルリク出しときます

**Comment by task4233** [comment]
Pythonのversion 3.9.6にしたら動いたとのこと
